# Generated by Django 3.2.12 on 2022-03-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='enabled_at',
            field=models.DateTimeField(default='2022-03-28T23:51:32.583431+00:00'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='Enabled', max_length=10),
        ),
    ]
