# Generated by Django 3.2.12 on 2022-03-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20220328_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='enabled_at',
            field=models.DateTimeField(default='2022-03-29T00:02:08.861181+00:00'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(choices=[('enabled', 'enabled'), ('disabled', 'disabled')], default='enabled', max_length=10),
        ),
    ]
