# Generated by Django 3.2.12 on 2022-03-29 00:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_token'),
        ('wallet', '0003_auto_20220329_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='enabled_at',
            field=models.DateTimeField(default='2022-03-29T00:35:23.481489+00:00'),
        ),
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'success'), ('unsuccesful', 'unsuccesful')], default='enabled', max_length=15)),
                ('withdrawn_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('reference_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
                ('withdrawn_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'success'), ('unsuccesful', 'unsuccesful')], default='enabled', max_length=15)),
                ('deposited_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('reference_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('deposited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
    ]
