# Generated by Django 3.2.12 on 2022-03-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20220329_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='enabled_at',
            field=models.DateTimeField(default='2022-03-29T01:25:26.330777+00:00'),
        ),
    ]
